In [1]:
import torch
print (torch.__version__)
x=torch.tensor([1,2,3,4,5])
print(x)
y=torch.tensor([[1,2],[3,4]])
print(y)


2.10.0+cpu
tensor([1, 2, 3, 4, 5])
tensor([[1, 2],
        [3, 4]])


In [2]:
torch.zeros(3,2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [3]:
torch.ones(2,2)


tensor([[1., 1.],
        [1., 1.]])

In [4]:
a=torch.rand(2,2)
print(a)
print(a.shape)


tensor([[0.6361, 0.7159],
        [0.3209, 0.0835]])
torch.Size([2, 2])


In [5]:
i=torch.tensor([10,20,30])
print(i[0])
print(i[1])

tensor(10)
tensor(20)


In [6]:
a=torch.tensor([1,2,3])
b=torch.tensor([4,5,6])
print(a+b)
print(a*b)

tensor([5, 7, 9])
tensor([ 4, 10, 18])


In [7]:
x=torch.tensor([[1,2],[3,4]])
y=torch.tensor([[5,6],[7,8]])
print(x+y)
print(x*y)  
# element wise multiplication
#Its not matrix multiplication

tensor([[ 6,  8],
        [10, 12]])
tensor([[ 5, 12],
        [21, 32]])


In [8]:
import numpy as np
arr=np.array([1,2,3])
n=torch.from_numpy(arr)
print(n)

tensor([1, 2, 3])


In [ ]:
import torch
x=torch.tensor([1.,2.,3.,4.])
print("x:",x)

y=torch.tensor([2.,4.,6.,8.])
print("y:",y)
w=torch.tensor(0.0)
b=torch.tensor(0.0)
print("w:",w)
print("b:",b)   

y_pred=w*x +b
print("y_pred:",y_pred)
loss=((y_pred-y)**2).mean()
print("loss:",loss)

x: tensor([1., 2., 3., 4.])
y: tensor([2., 4., 6., 8.])
w: tensor(0.)
b: tensor(0.)
y_pred: tensor([0., 0., 0., 0.])
loss: tensor(30.)
